- name: "Docker: install required system packages"
  apt:
    pkg:
      - ca-certificates
      - curl
    state: latest
    update_cache: true
  become: true

- name: "Docker: install keyrings"
  command:
    cmd: install -m 0755 -d /etc/apt/keyrings
  become: true

- name: "Docker: add a package repository"
  block:
    - name: "Docker: load GPG"
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '644'

    - name: "Docker: add a package repository"
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
  become: true

- name: "Docker: install packages"
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
  become: true
