- name: "Nvidia container toolkit: load GPG"
  shell:
    cmd: |
      curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | \
      gpg --yes --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg
  become: true

- name: "Nvidia container toolkit: create a package"
  shell:
    cmd: |
      curl -s -L https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list | \
      sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' | \
      tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  become: true

- name: "Nvidia container toolkit: install"
  apt:
    name: nvidia-container-toolkit
    state: latest
    update_cache: true
    autoclean: true
    autoremove: true
  become: true

- name: "Nvidia container toolkit: configure runtime"
  command:
    cmd: nvidia-ctk runtime configure --runtime=docker
  become: true

- name: "Nvidia container toolkit: restart docker engine"
  service:
    name: docker
    state: restarted
  become: true
