
- name: Set up a security group
  amazon.aws.ec2_security_group:
    name: geo-surreal-sg
    description: a security group for Geo Surreal
    vpc_id: "{{ ec2.vpc_id | default(omit) }}"
    region: "{{ ec2.region }}"
    rules:
    - rule_desc: SSH to install the software
      proto: tcp
      ports: [22]
      cidr_ip: 0.0.0.0/0
    - rule_desc: Geo Surreal application port
      proto: tcp
      ports: [4567]
      cidr_ip: 0.0.0.0/0
  register: security_group

- name: Set up an EC2 instance
  amazon.aws.ec2_instance:
    name: "{{ ec2.instance_name }}"

    instance_type: "{{ ec2.instance_type }}"
    image_id: "{{ ec2.ami_image_id }}"

    instance_role: "{{ ec2.instance_role }}"

    region: "{{ ec2.region }}"
    availability_zone: "{{ ec2.availability_zone | default(omit) }}"
    subnet_id: "{{ ec2.subnet_id | default(omit) }}"
    security_group: "{{ security_group.group_id }}"
    network:
      assign_public_ip: true
    key_name: "{{ ec2.key_name }}"

    volumes:
    - device_name: /dev/sda1
      ebs:
        volume_size: "{{ ec2.volume_size }}"
        volume_type: gp3
        delete_on_termination: true
    # - device_name: /dev/xvda1
    #   virtual_name: ephemeral0

    metadata_options:
      http_endpoint: enabled
      http_tokens: required

    state: "{{ ec2_state }}"
    wait: true

  register: server
