- name: Start Geo Surreal
  shell: "nohup ./geo-surreal > /dev/null 2>&1 &"
  args:
    chdir: /geo-surreal

- name: Wait for Geo Surreal to start
  wait_for:
    host: 0.0.0.0
    port: 4567
    timeout: 120
    delay: 6
    sleep: 1
    state: started

- name: Print the URL
  debug:
    msg:
    - Geo Surreal has started.
    - Check at http://{{ hostvars[inventory_hostname].ec2_public_dns_name }}:4567
