#!/bin/bash

if [ "$1" = "--stop" ]
then
    # stop all the docker containers
    sudo docker stop $(sudo docker ls -q –-filter ancestor=geo-sur)
else
    # start the docker container
    CWD=`pwd`

    sudo docker run --rm \
        --gpus all \
        -v $CWD/data:/data \
        -v $CWD/logs:/geo-sur/logs \
        -v $CWD/.database:/geo-sur/.database \
        -v $CWD/config.yml:/geo-sur/config.yml \
        -p 4567:4567 \
        -w /geo-sur --entrypoint="" \
        geo-sur ./geo-sur
fi
